### ISSUE TITLE
Where are notes stored; possible to sync its file with Syncthing?

### ISSUE THREAD

**Issue by gggirlgeek** [Sav22999/websites-notes#45]
Hi,

I haven't tried Notefox yet but I've installed it. It looks great. I've read through the issues but haven't found a clear answer to whether there is a way to sync notes between computers or Firefox profiles.

If Notefox stores its notes in a file(s) would it be possible to simply sync that file with something like Syncthing between Windows computers or even Android? (I don't sync my entire profile that way because, of course, having the profile open on 2 computers would be chaos. However, individual files might be possible??)

**Comment by Sav22999** [comment]
@gggirlgeek Hi! I actually cannot answer to the questioner "Where files are stored?". It's stored, apparently, in a database (https://stackoverflow.com/questions/7079075/where-does-firefox-store-javascript-html-localstorage).

I have tried to implement the syncing with Firefox account, but actually it was a problem because sync files have limited storage to 8KB and it's too low to sync all websites saved.

I'm so sorry.
You can use the "Import" and "Export" feature 😓
