### ISSUE TITLE
Support customised "sub-domains"

### ISSUE THREAD

**Issue by Sav22999** [Sav22999/websites-notes#49]
I asked you in the past about using * to add a note to more than one urls (https://github.com/Sav22999/websites-notes/issues/13 ). Sorry I didn't respond back then I had some issues with my github account. I'm not talking about some advanced pattern, just to be able to enter the * at the end of the selected part of url so it will match all with that prefix basically. There was one addon like that with the old ff and it used to be popular but as far as I know no addon nowdays provides that and I consider it a game changer. The main reason for a note addon is to be able to see the note if at sometime in the future u return back to the same url. There are websites that accept both x.y/z/ and x.y/z. If you revisit it (perhaps from a link) if it is not of the same form as when u wrote the note then u won't see the note. This is solved with * . Or there is something u want to keep in mind for a whole section of it but not for the whole domain, one easy example is qithub let's say I want to have a note regarding this repository https://github.com/Sav22999/websites-notes/*, or the developer, if I leave it on one of its pages whenever I visit some other I won't see it and if it is a repository I don't visit frequently I won't even remember it. And there are many other such cases: profiles in social networks where someone's profile has several different pages (\profilex\photos etc), same for tutorials or similar to github if your in the space of a specific item/software/.. in a portal that has many pages related to it, etc
(also in this subject if not difficult a choice to ignore the 1st part of url would be a welcome one as well = to display a note in all x.domain.com, y.domain.com and domain.com)
Probably that would be a solution for https://github.com/Sav22999/websites-notes/issues/19 as well

related to #46

**Comment by nik-gr** [comment]
(@Sav22999 since you separated my suggestions,  I guess here is a better a place to reply for this)

In my use cases the scenarios I thought was for website level, page level or/and only one "*" level but you are right if it is going to be implemented it's better to cover all possible cases

The easiest approach I can think of: 
4 labels: global | domain | * | page
each one to get a green/dark/.. color if there is a note there (so when the popup opens, the user will know what notes he wrote related to the page)
The * to display the 'closest' match in a not editable format 
The * to have a special field (or a field empty for the other labels) where it will show the url pattern for which the displayed note was written (perhaps at bottom above/below the update date)
By clicking the * label to  toggle between all (if any more) matching notes
If the user wants to add a " * " note, the addon first shall display a prompt with the current url so the user will choose the url pattern he wants and then open in editable format to write the note and if there is already a note for that specific pattern then like usual the written note will be displayed ready to get modified 
Perhaps also (if possible) to have a badge at the '*' label with the total number of the matching * patterns for the specific page

**Comment by Sav22999** [comment]
@nik-gr This would be very complicated to understand for a common user.
I'll think of it and how to implement, in case. Thanks!

**Comment by nik-gr** [comment]
ok, thanks! To be honest I don't find it that complicate from the scope of a user. Well, I gave it a try :) 
(it can always be as an advanced option enabled from settings so only users who want it will deal with it, although I do believe that most users will choose to use it)

**Comment by nik-gr** [comment]
great, thank you!!!
I don't know yet if it works as expected but as far as for ux/ui I think is great 👍
One small addition that I think will improve it: A different display (shadowed / a little different color / ..) at the labels that have notes. By labels I mean "Global", "Domain", "Page" and each subdomain label

I usually use the keyboard (instead of the mouse), do you think it's possible to add functionality that will allow the navigation to subdomain notes using keyboard? 
What I mean: As it is now with focus inside the note area (can go there easily with the addons shortcuts) I can press shift-tab + enter which is equal to mouse clicking on the 3 dots that open the options of subdomains but from there I cannot use keyboard to 'go' to them. 
(I know such a functionality won't be useful for almost all other users so I understand it's not worth to deal with it unless it is something that it's really easy to implement)

**Comment by Sav22999** [comment]
@nik-gr I'll fix in the next release. You'll be able to navigate pressing "Tab" (or Shift+Tab to get the previous element focussed). Thank you!

**Comment by nik-gr** [comment]
>  You'll be able to navigate pressing "Tab" (or Shift+Tab to get the previous element focussed)

thanks, looking forward to it!

One last thing that I related it to this the issue, the issue with '/' that I mentioned can appear also in the page notes (I'm guessing domain as well). I have such a note, it is for page https://developer.android.com/tools/adb/. If I visit it without the last '/' the note is not displayed (it is a Page note). Will it be possible to change that?

**Comment by Sav22999** [comment]
@nik-gr  Sorry, I haven't understood the issue

**Comment by Sav22999** [comment]
@nik-gr Ok, now I have understood. Basically if you visit the .../adb/ (with the /, it's considered as "Domain"), without it, instead, it's considered as "Page", as you said. I don't get that error 🤔 

It's weird it doesn't work properly

**Comment by Sav22999** [comment]
But the problem is that if a URL ends with "/" it is a directory (so not a Page), otherwise it is a Page -> I manage in this way to avoid issues (for example, if I include "/" in pages, when there is a page like https://..../index.php should I put "/" or not? Because a directory can have also name with ".").

I'm really sorry about this inconvenience, but actually this is not "a problem" related with the addon. I mean, if the websites "move" pages it's very problematic. This problematic I think is very uncommon, and I think it's useless insert many other conditions for this.
I hope you can understand, sorry

**Comment by nik-gr** [comment]
It can be solved if the note was left as subdomain note but to go like that you should have been aware that the website behaves this way so the note should be for subdomain instead of page. Which doesn't really help because what you want is to be able to see the notes you left when revisiting and it's impossible (and not practical) to know if a website accepts both ways of writing th url

**Comment by Sav22999** [comment]
@nik-gr Yes, exactly. It's very complicated... and this is only for some websites which decides to move files. I don't think I'll implement a check for this, sorry

**Comment by nik-gr** [comment]
(my previous post was before I saw your reply) 

>  when there is a page like https://..../index.php should I put "/" or not?

what I thought would be a solution was to ignore the last character if that character = /

But in any case yes, I am not aware of other web servers behaving like that. As long as it is exception it's not much of a problem, I agree
