### ISSUE TITLE
Improve searching feature supporting URL as well

### ISSUE THREAD

**Issue by Sav22999** [Sav22999/websites-notes#50]
Search: Can it be added a support to search multiple terms instead of one kewword/phrase as it is now (perhaps separated by comma)? And maybe adding the url in the searchable text?

Related to #46

**Comment by nik-gr** [comment]
thanks! did you decide to not implement the multi keyword search?

**Comment by Sav22999** [comment]
@nik-gr You're true! I've implemented an improved searching but I forgot to implement multi-keyword search. I'll think how to implement it (a good UX, as usual, and I'll implement 😄 )

So I reopen this issue

**Comment by nik-gr** [comment]
Perfect! And I have to repeat what an other user wrote, it's amazing your response time :)
what I had in mind was for a  note to be in the results  to have all of the keywords (main reason to use search is to find a specific note), the implementation gives results of all notes that have anyone of the keywords but that's ok as well, with good choice of keywords it covers the functionality I had in mind. 👍
I think it will be nice to have tooltip explaining how to use it

For any user may reading this:
you can search for different keywords by separating them with ';'
instead of a keyword you can give a whole phrase to be matched (leading and trailing empty spaces are not ignored)
it is an OR match: if a note matches any of the keywords then it will be in the results
search for match includes the text of the note itself, the url and the title of it

**Comment by Sav22999** [comment]
@nik-gr I'll add a tooltip to explain the multi-keys search feature 😊 thanks!
