### ISSUE TITLE
Notefox pop up gets closed as soon as open

### ISSUE THREAD

**Issue by AmirNaghibi** [Sav22999/websites-notes#84]
When I click on the notefox icon, the pop up to add note opens up but immediately gets closed. It does not let me add notes to it. 

Any suggestion on how to fix it?

Thanks

**Comment by Sav22999** [comment]
@AmirNaghibi Hi, firstly I'm sorry about this inconvenience.

Can you specify your web browser please?

**Comment by AmirNaghibi** [comment]
Thanks for your quick response!

I'm using Firefox. `Version 115.7.0esr (64-bit)`

**Comment by Sav22999** [comment]
@AmirNaghibi Ok, this is very weird 🤔  nobody reported this issue.

Maybe you can try to run a "temp session" of Firefox ([Troubleshoot Mode](https://support.mozilla.org/en-US/kb/troubleshoot-and-diagnose-firefox-problems#w_3-restart-firefox-in-troubleshoot-mode)) and try to enable only Notefox, because if in this way works it's not an issue related to Notefox but to something else

Please, let me know if this works

**Comment by AmirNaghibi** [comment]
Sounds good. I will do this tomorrow and let you know about the result.

**Comment by AmirNaghibi** [comment]
I have uninstalled another extension that was causing issues in my and notefox started working. 

here was the extension that was causing problems. https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

But I've also restarted my computer, that might have helped too.
